version: '3.9'

networks:
  lab:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '10.0.0.0/24'
          gateway: '10.0.0.100'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

configs:
  gitlab:
    file: ./confs/gitlab.rb

secrets:
  gitlab_root_password:
    file: ./confs/root_password.txt

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    domainname: quiver.net.br
    restart: on-failure:3
    command: --cleanup --schedule "0 0 * * * *" --debug watchtower gitlab
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
    deploy:
      resources:
        limits:
          memory: '128M'
        reservations:
          memory: '64M'
    networks:
      lab:
        ipv4_address: '10.0.0.10'

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: gitlab
    domainname: quiver.net.br
    restart: always
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
      - type: volume
        source: gitlab-config
        target: /etc/gitlab
      - type: volume
        source: gitlab-logs
        target: /var/log/gitlab
      - type: volume
        source: gitlab-data
        target: /var/opt/gitlab
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6G
        reservations:
          cpus: '2'
          memory: 2G
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
    ports:
      - '80:80'
      - '443:443'
    networks:
      lab:
        ipv4_address: '10.0.0.20'

  runner:
    image: gitlab/gitlab-runner:alpine
    container_name: runner
    restart: always
    hostname: runner
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      lab:
        ipv4_address: '10.0.0.30'
